matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
        - gcc-6
        - g++-6
    env:
      - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: osx
    osx_image: xcode9.4
language: c++
before_install:
- eval "${MATRIX_EVAL}"
- gcc -v && g++ -v 
- ./ci/before_install.sh
install:
- ./ci/install.sh
script:
- ./ci/savelibs.sh
